apiVersion: v1
kind: Secret
metadata:
  name: fair-visit-report-secret
  namespace: fair-visit-report
type: Opaque
stringData:
  POSTGRES_DB: "fair_reports"
  POSTGRES_USER: "fair_user"
  POSTGRES_PASSWORD: "fair_password"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=fair_reports;Username=fair_user;Password=fair_password"
