@version: 4.0

source s_network {
    network(
        ip("0.0.0.0")
        port(514)
        transport("udp")
    );
};

destination d_stdout {
    file("/dev/stdout");
};

destination d_alloy {
    syslog(
        "alloy"
        port(1514)
        transport("udp")
    );
};

log {
    source(s_network);
    destination(d_stdout);
    destination(d_alloy);
};